### ISSUE TITLE
Как проверить скорость загрузки?

### ISSUE THREAD

**Issue by k3fjeee** [ivknv/yadisk-async#3]
Привет!
У меня очень долго грузятся файлы на ЯД.
Каким образом я могу проверить скорость загрузки?

Файл в 6 мб он загружает минуту. Загрузку файла в 70мб я так и не дождался...

y = yadisk_async.YaDisk(token=config.ydisktoken)
					await y.upload(f'{file_path}', f'/logs/{filename}', timeout=None)
					url = await y.get_download_link(f'/logs/{filename}')
					await y.close()
					
					
С либой дропбокса загружает значительно быстрее, но она не асинхронна :(

**Comment by ivknv** [comment]
Самый простой способ &#8212; через диспетчер задач или другие внешние средства, если же вы хотите определить скорость в питоне, то можно сделать file-like объект (передать его вместо пути), переопределить метод read() и отслеживать чтение из файла (тоже самое можно сделать для скачивания через переопределение write).

Я попробовал залить большой файл библиотекой (~700 МБ), проблем со скоростью не обнаружил.
Но потом я попробовал загрузить файл с другим расширением (добавил .db к имени) и скорость большую часть времени была около нуля. Пару месяцев назад я сталкивался с такой проблемой, возможно у вас тоже самое, в таком случае это проблема самого Диска, не библиотеки.

Почему-то файлы с некоторыми определенными расширениями (как например .db) практически невозможно загрузить, скорость большую часть времени стремится к нулю. Возможно это связано с какой-нибудь забагованной проверкой антивируса, но это лишь догадка. Попробуйте позагружать файлы с другими расширениями.

**Comment by k3fjeee** [comment]
Это всего лишь .zip архив. Проблемой со скоростью при загрузке руками в тот-же каталог не возникает.

**Comment by ivknv** [comment]
Только что попробовал .zip подставить, такая-же фигня.

В браузере действительно нет проблемы, но я также пробовал использовать не-async версию библиотеки и даже заливать просто через curl по ссылке &#8212; проблема всё-таки есть. Я не совсем понимаю, почему в браузере всё нормально, но при использовании REST API явно что-то не так с загрузкой некоторых файлов, причем такое уже было раньше. Попробуйте загружать именно при помощи REST API.

**Comment by k3fjeee** [comment]
Я так понимаю это никак пофиксить нельзя?

**Comment by k3fjeee** [comment]
В итоге использую либу другого обменника.
