### ISSUE TITLE
почему выходит данная ошибка?

### ISSUE THREAD

**Issue by prtolem** [ivknv/yadisk-async#5]
aiohttp.client_exceptions.ServerTimeoutError: Timeout on reading data from socket

код:
```
path = 'Files/Videos/Results/video.mp4'
await y.upload(f, path.replace(path.split('/')[0] + "/", '').replace(path.split('/')[1] + "/", ''), n_retries=5, overwrite=True)
```

**Comment by ivknv** [comment]
Либо задан слишком маленький таймаут, либо это косяк Яндекс.Диска. Скорее всего последнее.
Issue [#16](https://github.com/ivknv/yadisk/issues/16):
> Кажется, это другая проблема. У Яндекс.Диска в последнее время какие-то проблемы с загрузкой файлов с определенными расширениями. На данный момент на Диск через REST API (в браузере всё в порядке) файлы грузятся до боли медленно (у меня вообще терпения не хватает, чтобы дождаться до конца). Проблему можно обойти только если указывать другое расширение файла, как бы глупо это не звучало.

> По неизвестным причинам не грузятся: *.db, *.zip и *.mp4 файлы (скорее всего и некоторые другие).
Эта проблема самого Яндекс.Диска, она не связана с этой библиотекой, такой же результат можно получить и через CURL.

> Совсем недавно у другого человека была такая же проблема, но только с async-версией: https://github.com/ivknv/yadisk-async/issues/3

**Comment by izhgtumekhanik** [comment]
Мб проблема в компоненте aiohttp?(в гугле много проблем всплывает с ним) я использую другой компонент на C# и без проблем грузятся файлы - да долго с zip, но эту ошибку он не выдает.

**Comment by izhgtumekhanik** [comment]
Traceback (most recent call last):

  File C:\Python38x64\lib\site-packages\spyder_kernels\py3compat.py:356 in compat_exec
    exec(code, globals, locals)

  File g:\сапр обработчики\ya disk\async.py:96
    loop.run_until_complete(summjob("4"))

  File C:\Python38x64\lib\site-packages\nest_asyncio.py:90 in run_until_complete
    return f.result()

  File C:\Python38x64\lib\asyncio\futures.py:178 in result
    raise self._exception

  File C:\Python38x64\lib\asyncio\tasks.py:280 in __step
    result = coro.send(None)

  File g:\сапр обработчики\ya disk\async.py:78 in summjob
    await ya.upload(f, "/destination.7z")

  File C:\Python38x64\lib\site-packages\yadisk_async\yadisk.py:779 in upload
    await self._upload(self.get_upload_link, path_or_file, dst_path, **kwargs)

  File C:\Python38x64\lib\site-packages\yadisk_async\yadisk.py:746 in _upload
    await auto_retry(attempt, n_retries, retry_interval)

  File C:\Python38x64\lib\site-packages\yadisk_async\utils.py:100 in auto_retry
    raise e

  File C:\Python38x64\lib\site-packages\yadisk_async\utils.py:95 in auto_retry
    return await func()

  File C:\Python38x64\lib\site-packages\yadisk_async\yadisk.py:742 in attempt
    async with session.put(link, data=data, **temp_kwargs) as response:

  File C:\Python38x64\lib\site-packages\aiohttp\client.py:1141 in __aenter__
    self._resp = await self._coro

  File C:\Python38x64\lib\site-packages\aiohttp\client.py:560 in _request
    await resp.start(conn)

  File C:\Python38x64\lib\site-packages\aiohttp\client_reqrep.py:899 in start
    message, payload = await protocol.read()  # type: ignore[union-attr]

  File C:\Python38x64\lib\site-packages\aiohttp\streams.py:616 in read
    await self._waiter

  File C:\Python38x64\lib\asyncio\futures.py:260 in __await__
    yield self  # This tells Task to wait for completion.

  File C:\Python38x64\lib\asyncio\tasks.py:349 in __wakeup
    future.result()

  File C:\Python38x64\lib\asyncio\futures.py:178 in result
    raise self._exception

ServerTimeoutError: Timeout on reading data from socket

Future exception was never retrieved
future: <Future finished exception=SSLError(1, '[SSL: APPLICATION_DATA_AFTER_CLOSE_NOTIFY] application data after close notify (_ssl.c:2758)')>
Traceback (most recent call last):
  File "C:\Python38x64\lib\asyncio\sslproto.py", line 529, in data_received
    ssldata, appdata = self._sslpipe.feed_ssldata(data)
  File "C:\Python38x64\lib\asyncio\sslproto.py", line 207, in feed_ssldata
    self._sslobj.unwrap()
  File "C:\Python38x64\lib\ssl.py", line 948, in unwrap
    return self._sslobj.shutdown()
ssl.SSLError: [SSL: APPLICATION_DATA_AFTER_CLOSE_NOTIFY] application data after close notify (_ssl.c:2758)

**Comment by izhgtumekhanik** [comment]
В файле C:\Python38x64\Lib\site-packages\aiohttp\client_proto.py
 функция:

```python
def _reschedule_timeout(self) -> None:
        timeout = self._read_timeout
        if self._read_timeout_handle is not None:
            self._read_timeout_handle.cancel()
        if timeout:
            self._read_timeout_handle = self._loop.call_later(
                timeout, self._on_read_timeout
            )
        else:
            self._read_timeout_handle = None
```

которая и вызывает ошибку.
Она не правильно принимает значение таймаута (если вывести ее значение(print(timeout)) то она ВСЕГДА принимает значение 15 и 4 цикла) 

Как только проходят 4 цикла - сразу ошибка эта.

Долго не думая прибавил 200 сек

```python
timeout = self._read_timeout + 200.0
```

теперь появились 2 ошибки:

1) PathExistsError: Ресурс "disk:/deston.zip" уже существует. (Resource "disk:/deston.zip" already exists. / DiskResourceAlreadyExistsError)
2) ClientConnectorError: Cannot connect to host cloud-api.yandex.net:443 ssl:default [getaddrinfo failed]

**Comment by izhgtumekhanik** [comment]
я не знающий: так и не смог понять откуда берутся 4 цикла и как они формируются и как изменить их.

**Comment by ivknv** [comment]
@izhgtumekhanik Судя по всему, у вас используется стандартный `timeout` (см. [параметры upload()](https://yadisk-async.readthedocs.io/ru/latest/docs.html#yadisk_async.YaDisk.upload)).

> ... откуда берутся 4 цикла и как они формируются и как изменить их.

По умолчанию в библиотеке заданы 3 повторные попытки для всех запросов (параметр `n_retries`), отсюда и 4 цикла с таймаутом по 15 сек. (значение по-умолчанию).

В `aiohttp` таймауты работают немного по другому, в отличие от, например, `requests`. В `aiohttp` read-timeout (`sock_read`) фактически означает таймаут на получение *полного ответа* от сервера, а в `requests` - таймаут на "молчание" сервера.
В итоге, если у вас файл заливается, например минуту, то вам придется указать таймаут (`sock_read`) не менее минуты (с `requests` бы этого не понадобилось).

**Comment by zoldaten** [comment]
думаю, это какие-то ошибки с Я.диском, т.к. залив .mp4 виснет как с async так и без него. файл без расширения заливается нормально.
вариант с async заливает файл одного и того же размера дольше, чем без async:
```
#0:01:06.442207 - 737Мб без расширения файла
#0:01:16.133977 - async без расширения файла
```
видимо, выигрыш будет при заливе нескольких файлов.

код с async из примера не работает без аргумента timeout. вот рабочий код:
```
async def main():
    print("token valid: ",await y.check_token())
    print("заливаю...")
    from datetime import datetime
    start = datetime.now()
    
    async with aiofiles.open("ghosted_1", "rb") as f:
        await y.upload(f, "/test-dir/ghosted_1",timeout=100)
    print("залил")
    
    #print(list(y.listdir("/test-dir")))
    print(datetime.now()- start)

if __name__ == '__main__':
  loop = asyncio.get_event_loop()
  loop.run_until_complete(main())
  loop.close()
```

не смотря на то, что timeout=100, все работает, а вот без него уже нет.

**Comment by izhgtumekhanik** [comment]
Значения таймаута носят магический характер.. это как пальцем в небо и нет не какой надежности..
Избыточное значение приводит к перезаписи а недостаток к недозапсии - я пока не пойму как победить это..
Вот пример из C# - работает как часы ...

```csharp
//загружаем файл (zipitog - архив)
Link link = await api.Files.GetUploadLinkAsync("/" + FolderDateNew + "/" + FileDiskName, overwrite:false).ConfigureAwait(true);
using (var fs = System.IO.File.OpenRead(zipitog))
{
	await api.Files.UploadAsync(link, fs);
}

Link resultPP = await api.MetaInfo.PublishFolderAsync("/" + FolderDateNew + "/" + FileDiskName).ConfigureAwait(true);
Resource fooResourceDescription = await api.MetaInfo.GetInfoAsync(new ResourceRequest {Path = "/" + FolderDateNew + "/" + FileDiskName}, CancellationToken.None);

// получаем публичную ссылку
string pubLink = fooResourceDescription.PublicUrl;
```

**Comment by ivknv** [comment]
@izhgtumekhanik Из-за того, что библиотека внутри использует `aiohttp`, поменять механизм таймаутов нельзя.
С другой стороны, я мог бы просто заменить `aiohttp` на `httpx`, у `httpx`, судя по всему, нет такой проблемы с таймаутами. Единственный минус такого решения - нарушение совместимости, небольшие отличия все-таки есть.

Я пока еще только рассматриваю `httpx` как вариант, если задумаю переход, то заранее упомяну это где-нибудь в README или создам отдельный issue.

**Comment by izhgtumekhanik** [comment]
Из всех вариантов которые попробовал у aiohttp - самая быстрая загрузка на диск - забирает почти всю скорость интернета на выгрузку -- что очень удобно.

**Comment by izhgtumekhanik** [comment]
> думаю, это какие-то ошибки с Я.диском, т.к. залив .mp4 виснет как с async, так и без него. файл без расширения заливается нормально. вариант с async заливает файл на один и тот же размер дольше, чем без async:
> 

Похоже их пофиксили..

В общем нашел время и вот что вышло - https://github.com/ivknv/yadisk-async/issues/8
