### ISSUE TITLE
Ошибка при выгрузке файла через aiofiles

### ISSUE THREAD

**Issue by youngive** [ivknv/yadisk-async#7]
async with aiofiles.open(path+name, "rb") as f:
        await y.upload(f, yadp+"/"+name.split(file_ext)[0]+xxx_ext, overwrite=True)

await auto_retry(attempt, n_retries, retry_interval)  File "/usr/local/lib/python3.7/site-packages/yadisk_async/utils.py", line 86, in auto_retry    return await func()  File "/usr/local/lib/python3.7/site-packages/yadisk_async/functions/resources.py", line 515, in attempt    async with session.put(link, data=UnclosableFile(file), **temp_kwargs) as response:  File "/usr/local/lib/python3.7/site-packages/aiohttp/client.py", line 1141, in aenter    self._resp = await self._coro  File "/usr/local/lib/python3.7/site-packages/aiohttp/client.py", line 560, in _request    await resp.start(conn)  File "/usr/local/lib/python3.7/site-packages/aiohttp/client_reqrep.py", line 899, in start    message, payload = await [protocol.read](http://protocol.read/)()  # type: ignore[union-attr]  File "/usr/local/lib/python3.7/site-packages/aiohttp/streams.py", line 616, in read
    await self._waiter  File "/usr/local/lib/python3.7/site-packages/aiohttp/client_reqrep.py", line 581, in write_bytes    await self.body.write(writer)  File "/usr/local/lib/python3.7/site-packages/aiohttp/payload.py", line 306, in write
    await writer.write(chunk)  File "/usr/local/lib/python3.7/site-packages/aiohttp/http_writer.py", line 112, in write    chunk_len_pre = ("%x\r\n" % len(chunk)).encode("ascii")
TypeError: object of type 'generator' has no len()

Python 3.7.3

**Comment by ivknv** [comment]
Поддержка aiofiles появиласть в версии 1.4.0. Начиная с этой версии требуется Python>=3.8.0. Скорее всего у вас yadisk_async 1.3.6 и поэтому такая ошибка.

**Comment by 666young** [comment]
Да, 1.3.6. Я бы рад использовать новейшие интерпретаторы, но там ssl ошибки с pip'ом на Debian 9. 
Спасибо за информацию, откатил изменения :)

**Comment by youngive** [comment]
> Поддержка aiofiles появиласть в версии 1.4.0. Начиная с этой версии требуется Python>=3.8.0. Скорее всего у вас yadisk_async 1.3.6 и поэтому такая ошибка.

Да, 1.3.6. Я бы рад использовать новейшие интерпретаторы, но там ssl ошибки с pip'ом на Debian 9.
Спасибо за информацию, откатил изменения :)
