### ISSUE TITLE
Как собрать универсальную функцию загрузки файла на диск ?

### ISSUE THREAD

**Issue by izhgtumekhanik** [ivknv/yadisk-async#8]
Спасибо за прикольный модуль! 

Нужна стабильная и надежная функция которая бы загружала файл на диск и не как не могу собрать ее..

что известно: SpeedUpl - скорость интернета отдачи
FileW - вес файла

1) Непонятно почему таймаут получает **None**
В файле \Lib\site-packages\aiohttp\client_proto.py
функция:

```python
def _reschedule_timeout(self) -> None:
        timeout = self._read_timeout
        print(timeout) # - почему то None
        if self._read_timeout_handle is not None:
            self._read_timeout_handle.cancel()

        if timeout:
            self._read_timeout_handle = self._loop.call_later(
                timeout, self._on_read_timeout
            )
        else:
            self._read_timeout_handle = None
```
делаю так (если удалю таймаут 20 то функция выше таймаут получает значение по умолчанию 15)

```python
async with aiofiles.open(r"home\syncfusion-file-formats.zip", "rb") as f:
    await ya.upload(f, "/destons.zip", timeout=20.0, n_retries=6)
    f.close()
```

2) если задать большой таймаут и большое число циклов то я все равно получаю ошибки..

1. PathExistsError: Ресурс "disk:/deston.zip" уже существует. (Resource "disk:/deston.zip" already exists. / DiskResourceAlreadyExistsError)
2. ClientConnectorError: Cannot connect to host cloud-api.yandex.net:443 ssl:default [getaddrinfo failed]
3. ServerTimeoutError: Timeout on reading data from socket
Future exception was never retrieved
future: <Future finished exception=SSLError(1, '[SSL: APPLICATION_DATA_AFTER_CLOSE_NOTIFY] application data after close notify (_ssl.c:2758)')>
Traceback (most recent call last):
File "C:\Python38x64\lib\asyncio\sslproto.py", line 529, in data_received
ssldata, appdata = self._sslpipe.feed_ssldata(data)
File "C:\Python38x64\lib\asyncio\sslproto.py", line 207, in feed_ssldata
self._sslobj.unwrap()
File "C:\Python38x64\lib\ssl.py", line 948, in unwrap
return self._sslobj.shutdown()
ssl.SSLError: [SSL: APPLICATION_DATA_AFTER_CLOSE_NOTIFY] application data after close notify (_ssl.c:2758)

странно что когда файл загрузился - он не завершает работу а продолжает заново грузить выдавая ошибку о PathExistsError
тут можно поймать исключение.. - есть подозрение что файл грузится не полностью..

Как собрать стабильную функцию пусть хоть с запасом 150% от времени ?

**Comment by izhgtumekhanik** [comment]
Есть библа на C# там тоже асинхронная работа, но там нет ошибок с ServerTimeoutError: Timeout on reading data from socket..
Она тоже грузит медленно файлы zip и др. но ошибку такую не выдает.

**Comment by ivknv** [comment]
> странно что когда файл загрузился - он не завершает работу а продолжает заново грузить выдавая ошибку о PathExistsError
тут можно поймать исключение.. - есть подозрение что файл грузится не полностью..

Насколько я знаю, даже если не дождаться ответа от сервера (например, из-за таймаута), Яндекс.Диск считает файл загруженным, если он получил файл целиком, так работает REST.API. Возможно, в вашем случае причина ошибки в этом.

Избежать эту ошибку можно 2 способами:
1) задать `overwrite=True`, чтобы перезаписывать файл, если он уже существует;
2) сделать таймаут больше.

Стоит также учитывать, что даже после того, как вы полностью загрузили файл, сервер может не отвечать продолжительное время (в некоторых случаях до минуты, возможно даже больше).

Примерный таймаут можно посчитать как `FileW / SpeedUpl`.
Таймаут лучше указывать в виде объекта `aiohttp.ClientTimeout`, с помощью него можно задать отдельные таймауты для установления соединения и для самого запроса.

Вы можете использовать что-нибудь подобное:
```python

# Базовый таймаут, независящий от файла
baseline_read_timeout = 60.0

async with aiofiles.open(r"home\syncfusion-file-formats.zip", "rb") as f:
    read_timeout = FileW / SpeedUpl + baseline_read_timeout
    timeout = aiohttp.ClientTimeout(sock_connect=10, sock_read=read_timeout)

    await ya.upload(f, "/destons.zip", timeout=timeout, n_retries=6)
```

Из-за упомянутого выше нюанса работы API, лучше указывать `overwrite=True`, если перезапись файла не вызывает проблем.
Можно также просто ловить исключение `PathExistsError`, но в таком случае лучше убедиться в целостности загруженного файла.

**Comment by izhgtumekhanik** [comment]
Спасибо! 
Но функция все равно не надежная, вот что удалось собрать:

```python
import yadisk_async
import asyncio
import nest_asyncio
import aiofiles
import ssl
import certifi


ya = yadisk_async.YaDisk(token='token')

# асинхронный последовательный поток
async def upl_Y():
        
    ...
    # предыдущая задача
    ...

    while True:

        ssl_context = ssl.create_default_context(cafile=certifi.where())
        
        # Базовый таймаут, независящий от файла
        baseline_read_timeout = 60.0
        
        try:
            
            async with aiofiles.open(r"home\syncfusion-file-formats.zip", "rb") as f:
                
                read_timeout = FileW / SpeedUpl + baseline_read_timeout
                timeout = aiohttp.ClientTimeout(sock_connect=10, sock_read=read_timeout)
            
                await ya.upload(f, "/destons.zip", timeout=timeout, n_retries=6, ssl_context=ssl_context)
                
            break
            
        except yadisk.exceptions.PathExistsError:
            
            '''
            вероятно файл загружен 
            тут его скачиваем и сверяем хеш сумму 
            и убеждаемся в этом
            '''
            
            break
        
        except:
            # по новой грузим
            continue

    ...
    # последующая задача
    ...
    
async def nextjob():
    ...

# policy = asyncio.WindowsSelectorEventLoopPolicy()
# loop = asyncio.set_event_loop_policy(policy)

loop = asyncio.get_event_loop()
nest_asyncio.apply(loop)

loop.run_until_complete(upl_Y())
loop.run_until_complete(nextjob())
```

**Comment by izhgtumekhanik** [comment]
В случае с большими файлами - как вариант при архивировании разделить архивы(или просто разделить файл) на малые веса:
1) по стабильнее будет работа;
2) закрепление прогресса закачки - с большим файлом заново придется все грузить и больше времени уйдет;
3) уменьшенные тайминги что в сумме дадут меньше расхода времени;

**Comment by izhgtumekhanik** [comment]
В общем можно проще реализовать..
Признак наличия файла на диске уже говорит о его загруженности, тогда:

```python
# загрузка файла ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
async def uploadefile(file_path1, file_path2, y):
    await y.upload(file_path1, file_path2, timeout=999999)

#проверка существования файла
async def file_exist(file_path2, flag, y):  
    flag.value = False
    
    while not flag.value:
        # не думаю что можно уменьшить значение 10 тайминга тк приведет к нагрузке сервера а это предупреждение/бан
        time.sleep(10)
        with flag.get_lock():
                flag.value = await y.exists(file_path2)
                if flag.value:
                        break

def func11(file_path1, file_path2, y):
    print('func11', flush=True)
    loop22 = asyncio.get_event_loop()
    nest_asyncio.apply(loop22)
    loop22.run_until_complete(uploadefile(file_path1, file_path2, y))
    loop22.stop()
    
def func22(file_path2, flag, y):
    print('func22', flush=True)
    loop11 = asyncio.get_event_loop()
    nest_asyncio.apply(loop11)
    loop11.run_until_complete(file_exist(file_path2, flag, y))
    loop11.stop()

if __name__ == '__main__':
    y = yadisk_async.YaDisk(token=t2)

    flag = multiprocessing.Value('b', False)
    
    file_path1 = r"Z:\мусор\dgfff"
    file_path2 = "disk:/TestFolder/gfg22.rdw"
    
    process1 = multiprocessing.Process(target=func11, args=(file_path1, file_path2, y,))
    process2 = multiprocessing.Process(target=func22, args=(file_path2, flag, y,)) 
    
    process1.start()
    process2.start()
    
    while not flag.value:
        time.sleep(2)
        print(flag.value)
        
    process1.terminate()
    process2.terminate()
    
    process1.join()
    process2.join()
```

В общем загрузка очень быстрая по сравнению с yadisk.

**Comment by izhgtumekhanik** [comment]
Иногда ошибку выбивает:
`
Unclosed client session
client_session: <yadisk_async.session.SessionWithHeaders object at 0x0000020X7C0ESF111>
`
