### ISSUE TITLE
Есть ли ограничения на количество одновременных подключений к диску ?

### ISSUE THREAD

**Issue by izhgtumekhanik** [ivknv/yadisk-async#9]
Простите за глупый вопрос, я где то видел что нельзя более 10 одновременных коннектов к диску это так ? Если так то как отловить количество активных пользователей диска ?

Я хочу диск использовать для чата и передачи файлов, какое исключение выйдет если одновременно в чат войдут более 10 человек ?
Спасибо.

**Comment by ivknv** [comment]
> где то видел что нельзя более 10 одновременных коннектов к диску

Явного ограничения на количество одновременных соединений, насколько мне известно, нет. При этом есть ограничение на частоту запросов. В общем случае, можно спокойно использовать 5-7 параллельных соединений. Насколько я понимаю, ограничения применяются отдельно для каждого аккаунта пользователя.

> какое исключение выйдет если одновременно в чат войдут более 10 человек

Если превышено ограничение на частоту запросов, то библиотека вызовет исключение [TooManyRequestsError](https://yadisk-async.readthedocs.io/ru/latest/docs.html#yadisk_async.exceptions.TooManyRequestsError).

**Comment by izhgtumekhanik** [comment]
> Возможно, я допускаю ограничения, применяемые отдельно для каждого аккаунта пользователя.

Я тоже так считаю если приобрести например премиум пакет. Спасибо!
